"""Music support shared by the mock and real generation paths.

The package provides three cooperating pieces:

- :mod:`planner` groups scenes into long musical movements (tens of seconds,
  never per-scene stings) with a stable energy curve derived from scene moods.
- :mod:`synth` is a deterministic, dependency-free procedural composer used by
  the mock backend so development renders contain actual music (harmony,
  bass, melody, percussion) instead of a sine tone.
- :mod:`stitch` joins per-movement audio files into the single
  ``music/background.wav`` consumed by the timeline and renderer.
- :mod:`score` defines the Score Studio cue plan (timed pullbacks, silences,
  impacts) over the generated soundtrack, its validation, and its atomic
  persistence as ``music/score-plan.json``.
"""

from .planner import MovementPlan, energy_for_mood, plan_hash, plan_movements
from .autoscore import (
    AUTO_SCORE_JSON_SCHEMA,
    LOCKED_CUE_COLLISION_SECONDS,
    AutoScoreProposal,
    AutoScoreSuggestion,
    apply_auto_score_suggestions,
    build_auto_score_prompt,
    deterministic_auto_score,
    llm_auto_score,
    validate_auto_score_payload,
)
from .score import (
    DEFAULT_BUILD_DB,
    DEFAULT_PULL_BACK_DB,
    EFFECTS_DIRECTORY,
    EFFECT_ACTIONS,
    SCORE_MIX_MANIFEST_FILENAME,
    SCORE_MIX_WORKFLOW_VERSION,
    SCORE_MEDIA_FILES,
    SCORE_PLAN_FILENAME,
    SCORE_PLAN_VERSION,
    SCORE_PREVIEW_FILENAME,
    SCORE_PREVIEW_MANIFEST_FILENAME,
    SCORE_PREVIEW_WORKFLOW_VERSION,
    SCORED_OUTPUT_FILENAME,
    SCORED_SAMPLE_RATE,
    ScoreAction,
    ScoreCue,
    ScoreCueSource,
    ScorePlan,
    ScorePlanConflict,
    ScoreRenderError,
    compile_music_envelope,
    decode_stereo_pcm,
    empty_score_plan,
    encode_stereo_pcm,
    hash_audio_file,
    load_score_mix_manifest,
    load_score_plan,
    load_score_preview_manifest,
    mix_stereo,
    render_scored_background,
    render_score_preview,
    resolve_cue_effect_path,
    save_score_plan,
    score_mix_manifest_path,
    score_plan_hash,
    score_plan_path,
    score_preview_manifest_path,
    score_preview_path,
    scored_background_path,
    validate_score_plan_effects,
)
from .synth import (
    SAMPLE_RATE,
    apply_edge_fades,
    compose_movement,
    compose_movement_frames,
    read_wav_frames,
    stitch_dips,
    write_wav,
)

__all__ = [
    "SAMPLE_RATE",
    "DEFAULT_BUILD_DB",
    "DEFAULT_PULL_BACK_DB",
    "EFFECTS_DIRECTORY",
    "EFFECT_ACTIONS",
    "MovementPlan",
    "SCORE_MIX_MANIFEST_FILENAME",
    "SCORE_MIX_WORKFLOW_VERSION",
    "SCORE_MEDIA_FILES",
    "SCORE_PLAN_FILENAME",
    "SCORE_PLAN_VERSION",
    "SCORE_PREVIEW_FILENAME",
    "SCORE_PREVIEW_MANIFEST_FILENAME",
    "SCORE_PREVIEW_WORKFLOW_VERSION",
    "SCORED_OUTPUT_FILENAME",
    "SCORED_SAMPLE_RATE",
    "ScoreAction",
    "ScoreCue",
    "ScoreCueSource",
    "ScorePlan",
    "ScorePlanConflict",
    "ScoreRenderError",
    "AUTO_SCORE_JSON_SCHEMA",
    "AutoScoreProposal",
    "AutoScoreSuggestion",
    "build_auto_score_prompt",
    "llm_auto_score",
    "validate_auto_score_payload",
    "apply_edge_fades",
    "compile_music_envelope",
    "compose_movement",
    "compose_movement_frames",
    "decode_stereo_pcm",
    "empty_score_plan",
    "encode_stereo_pcm",
    "energy_for_mood",
    "hash_audio_file",
    "load_score_mix_manifest",
    "load_score_plan",
    "load_score_preview_manifest",
    "mix_stereo",
    "plan_hash",
    "plan_movements",
    "read_wav_frames",
    "render_scored_background",
    "render_score_preview",
    "resolve_cue_effect_path",
    "save_score_plan",
    "score_mix_manifest_path",
    "score_plan_hash",
    "score_plan_path",
    "score_preview_manifest_path",
    "score_preview_path",
    "scored_background_path",
    "stitch_dips",
    "validate_score_plan_effects",
    "write_wav",
]
