"""Score plan: timeline cues over the generated soundtrack, plus persistence.

ACE-Step composes the underlying music but does not honor exact timestamps.
Exact musical moves (pullbacks, silences, impacts) are therefore described by
a *score plan* that is applied afterward, deterministically, by FFmpeg:

    music/background.wav  +  music/score-plan.json  ->  music/scored-background.wav

``background.wav`` is never modified; it remains the original generated master.

The models here define the portable, human-readable ``score-plan.json``
schema (version 1), validate every cue, and read/write the plan atomically.
Rendering the automation into audio is a separate concern (the deterministic
``score_mix`` pipeline stage) that consumes exactly these models.
"""

from __future__ import annotations

import hashlib
import json
import math
import os
import re
import subprocess
import tempfile
import wave
from array import array
from dataclasses import dataclass
from datetime import datetime
from enum import StrEnum
from pathlib import Path
from typing import Any

from pydantic import Field, field_validator, model_validator

from backend.rendering.binaries import FFmpegBinaries, require_ffmpeg
from backend.rendering.process import run_media_process
from backend.schemas.models import DomainModel, new_id, utc_now
from backend.schemas.paths import portable_relative_path, resolve_project_path

#: Portable schema version written by this module and the only one accepted
#: when loading. Older or newer files require an explicit migration.
SCORE_PLAN_VERSION = 1

#: Project-relative artifact names (inside ``<project>/music/``).
SCORE_PLAN_FILENAME = "score-plan.json"
SCORED_OUTPUT_FILENAME = "scored-background.wav"
EFFECTS_DIRECTORY = "music/effects"

#: Guardrail bounds shared with the score renderer and the Score Studio UI.
MAX_TRANSITION_SECONDS = 5.0
GAIN_DB_MIN = -60.0
GAIN_DB_MAX = 12.0
LOWPASS_HZ_MIN = 200.0
LOWPASS_HZ_MAX = 20_000.0
#: Sanity bound for soundtrack/plan duration: 24 hours.
MAX_DURATION_SECONDS = 24 * 3600

DEFAULT_CUE_TRANSITION_SECONDS = 0.25

_HEX_HASH = re.compile(r"^[0-9a-f]{8,64}$")


class ScoreAction(StrEnum):
    """MVP cue vocabulary.

    Music-automation actions reshape the background bed from their cue time
    onward; effect actions mix a one-shot asset in at the cue time.
    """

    BUILD = "build"
    PULL_BACK = "pull_back"
    SILENCE = "silence"
    RESTORE = "restore"
    IMPACT = "impact"
    RISER = "riser"
    END_STING = "end_sting"


#: Actions that change the music envelope (gain/filter automation).
MUSIC_AUTOMATION_ACTIONS = frozenset(
    {ScoreAction.BUILD, ScoreAction.PULL_BACK, ScoreAction.SILENCE, ScoreAction.RESTORE}
)
#: Actions that mix in a one-shot audio asset.
EFFECT_ACTIONS = frozenset(
    {ScoreAction.IMPACT, ScoreAction.RISER, ScoreAction.END_STING}
)


class ScoreCueSource(StrEnum):
    """Where a cue came from; Auto Score must never overwrite MANUAL cues."""

    MANUAL = "manual"
    AUTO = "auto"


class ScorePlanConflict(RuntimeError):
    """The plan changed on disk since the caller last read it."""


class ScoreCue(DomainModel):
    """One timed musical move on the soundtrack timeline.

    Field relevance depends on ``action``: automation cues use
    ``gain_db``/``lowpass_hz``/``transition_seconds``; effect cues use
    ``effect_asset_id``/``effect_path``/``effect_gain_db``. ``gain_db`` is a
    *relative* offset in dB for build/pull_back (from the level the previous
    cue left behind), an *absolute* target for restore, and ignored by
    silence. Irrelevant fields are preserved (not rejected) so round-trips
    are lossless, and the renderer ignores them.
    """

    # Stable identity: assigned once at creation, never regenerated by
    # sorting, editing order, or persistence round-trips.
    id: str = Field(default_factory=new_id, min_length=1, max_length=64)
    time_seconds: float = Field(ge=0, le=MAX_DURATION_SECONDS, allow_inf_nan=False)
    action: ScoreAction
    label: str = Field(default="", max_length=200)
    transition_seconds: float = Field(
        default=DEFAULT_CUE_TRANSITION_SECONDS,
        ge=0,
        le=MAX_TRANSITION_SECONDS,
        allow_inf_nan=False,
    )
    # Music automation parameters (automation cues only).
    gain_db: float | None = Field(
        default=None, ge=GAIN_DB_MIN, le=GAIN_DB_MAX, allow_inf_nan=False
    )
    lowpass_hz: float | None = Field(
        default=None, ge=LOWPASS_HZ_MIN, le=LOWPASS_HZ_MAX, allow_inf_nan=False
    )
    # Effect sourcing (effect cues only). ``effect_path`` is a portable
    # project-relative path; ``effect_asset_id`` refers to a registered
    # project effect asset.
    effect_asset_id: str | None = Field(default=None, min_length=1, max_length=100)
    effect_path: str | None = Field(default=None, max_length=500)
    effect_gain_db: float | None = Field(
        default=None, ge=GAIN_DB_MIN, le=GAIN_DB_MAX, allow_inf_nan=False
    )
    source: ScoreCueSource = ScoreCueSource.MANUAL
    locked: bool = False

    @field_validator("effect_path", mode="before")
    @classmethod
    def portable_effect_path(cls, value: Any) -> Any:
        if value is None or isinstance(value, str):
            if value is None:
                return None
            # Rejects absolute paths, drive letters, UNC, and .. traversal
            # before the value is ever persisted.
            return portable_relative_path(value)
        return value


class ScorePlan(DomainModel):
    """Portable cue plan over one generated soundtrack.

    ``source_music_hash`` and ``source_backend`` record where the scored
    master came from; ``revision`` is the monotonic save counter used for
    optimistic concurrency; cues are always ordered by ``time_seconds``.
    """

    version: int = SCORE_PLAN_VERSION
    duration_seconds: float = Field(
        gt=0, le=MAX_DURATION_SECONDS, allow_inf_nan=False
    )
    source_music_hash: str | None = None
    source_backend: str = Field(default="unknown", max_length=80)
    revision: int = Field(default=1, ge=0)
    updated_at: datetime = Field(default_factory=utc_now)
    cues: list[ScoreCue] = Field(default_factory=list)

    @field_validator("version")
    @classmethod
    def supported_version(cls, value: int) -> int:
        if value != SCORE_PLAN_VERSION:
            raise ValueError(
                f"unsupported score plan version {value}; this build reads version {SCORE_PLAN_VERSION}"
            )
        return value

    @field_validator("source_music_hash", mode="before")
    @classmethod
    def normalize_source_hash(cls, value: Any) -> Any:
        if value is None:
            return None
        if isinstance(value, str):
            text = value.strip().lower()
            if not text:
                return None
            if not _HEX_HASH.fullmatch(text):
                raise ValueError("source_music_hash must be a hex sha256 digest")
            return text
        return value

    @model_validator(mode="after")
    def normalize_and_validate_cues(self) -> "ScorePlan":
        ids = [cue.id for cue in self.cues]
        if len(ids) != len(set(ids)):
            duplicates = sorted({i for i in ids if ids.count(i) > 1})
            raise ValueError(f"duplicate cue ids: {', '.join(duplicates)}")
        # Deterministic ordering: stable sort keeps equal-time cues in input
        # order and carries each cue's id along with it.
        ordered = sorted(self.cues, key=lambda cue: cue.time_seconds)
        if ordered != self.cues:
            object.__setattr__(self, "cues", ordered)
        for cue in self.cues:
            if cue.time_seconds > self.duration_seconds:
                raise ValueError(
                    f"cue {cue.id} at {cue.time_seconds}s is past the end of the "
                    f"soundtrack ({self.duration_seconds}s)"
                )
        return self


def empty_score_plan(
    duration_seconds: float,
    *,
    source_music_hash: str | None = None,
    source_backend: str = "unknown",
) -> ScorePlan:
    """A valid, cue-less plan for a soundtrack of the given length."""
    return ScorePlan(
        duration_seconds=duration_seconds,
        source_music_hash=source_music_hash,
        source_backend=source_backend,
    )


def score_plan_path(project_root: Path) -> Path:
    return project_root / "music" / SCORE_PLAN_FILENAME


def scored_background_path(project_root: Path) -> Path:
    """Render target consumed by the timeline; never overwrites background.wav."""
    return project_root / "music" / SCORED_OUTPUT_FILENAME


def load_score_plan(project_root: Path) -> ScorePlan | None:
    """Read and validate the plan, or ``None`` when the project is unscored.

    A missing file is the normal "no score" state. A malformed plan raises so
    callers can surface the problem instead of silently ignoring cues.
    """
    path = score_plan_path(project_root)
    if not path.is_file():
        return None
    return ScorePlan.model_validate_json(path.read_text(encoding="utf-8"))


def save_score_plan(
    project_root: Path,
    plan: ScorePlan,
    *,
    expected_revision: int | None = None,
) -> ScorePlan:
    """Atomically persist ``plan`` and return the saved plan.

    With ``expected_revision`` set, the plan on disk must still carry that
    revision (0 when absent): a stale editor gets :class:`ScorePlanConflict`
    instead of silently overwriting newer work, and the saved copy is stamped
    with ``expected_revision + 1``. Without it the caller keeps full control
    of the revision (internal tooling, migrations).
    """
    current = load_score_plan(project_root)
    current_revision = current.revision if current is not None else 0
    if expected_revision is not None and current_revision != expected_revision:
        raise ScorePlanConflict(
            "score plan changed since it was loaded: expected revision "
            f"{expected_revision}, found {current_revision}"
        )
    updates: dict[str, Any] = {"updated_at": utc_now()}
    if expected_revision is not None:
        updates["revision"] = current_revision + 1
    saved = plan.model_copy(update=updates)
    _atomic_write_json(score_plan_path(project_root), saved.model_dump(mode="json"))
    return saved


def score_plan_hash(plan: ScorePlan) -> str:
    """Stable 16-hex content digest of the score.

    Ignores ``revision`` and ``updated_at`` so re-saving an unchanged score
    (or bumping provenance metadata) never changes the digest; the score_mix
    stage uses this as its cache key alongside the source music hash.
    """
    payload: dict[str, Any] = {
        "version": plan.version,
        "duration_seconds": round(plan.duration_seconds, 6),
        "source_music_hash": plan.source_music_hash,
        "cues": [cue.model_dump(mode="json") for cue in plan.cues],
    }
    return hashlib.sha256(
        json.dumps(payload, sort_keys=True, ensure_ascii=False).encode("utf-8")
    ).hexdigest()[:16]


def hash_audio_file(path: Path, *, block_size: int = 1024 * 1024) -> str:
    """Streaming sha256 of a soundtrack/effect file, for plan provenance."""
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        while True:
            chunk = handle.read(block_size)
            if not chunk:
                break
            digest.update(chunk)
    return digest.hexdigest()


def resolve_cue_effect_path(project_root: Path, cue: ScoreCue) -> Path | None:
    """Resolve a cue's project-relative effect path, rejecting escapes.

    Raises ``ValueError`` for traversal or symlink escapes; returns ``None``
    when the cue references an asset registry id instead of a path.
    """
    if cue.effect_path is None:
        return None
    return resolve_project_path(project_root, cue.effect_path)


def validate_score_plan_effects(project_root: Path, plan: ScorePlan) -> None:
    """Check every effect reference on a cue plan against the project tree.

    Paths must resolve inside the project directory (no traversal, no symlink
    escapes) and point at an existing file. Asset-id references are resolved
    by the effect registry layer and are skipped here.
    """
    problems: list[str] = []
    for cue in plan.cues:
        if cue.effect_path is None:
            continue
        try:
            resolved = resolve_cue_effect_path(project_root, cue)
        except ValueError as exc:
            problems.append(f"cue {cue.id}: {exc}")
            continue
        if resolved is not None and not resolved.is_file():
            problems.append(
                f"cue {cue.id}: effect file not found: {cue.effect_path}"
            )
    if problems:
        raise ValueError("; ".join(problems))


def _atomic_write_json(path: Path, payload: Any) -> None:
    """Crash-safe JSON write matching the project store's conventions."""
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{path.name}.", dir=path.parent
    )
    temporary = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
            json.dump(payload, handle, indent=2, sort_keys=True, ensure_ascii=False)
            handle.write("\n")
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary, path)
    except Exception:
        temporary.unlink(missing_ok=True)
        raise


# ---------------------------------------------------------------------------
# Deterministic score renderer
#
# ACE-Step composes the music; exact cues are applied here, afterwards. The
# mix is sample-accurate (gain steps land on the exact sample of the cue time)
# so a silence cue is silent from its requested moment and an impact is
# audible exactly when the narration demands it. FFmpeg normalizes the
# background and effect files to 48 kHz stereo PCM before the mix; the mix
# itself and the output write are pure, dependency-free DSP. No
# loudness-normalization is ever applied after cue automation: the generated
# soundtrack is already normalized upstream, and re-normalizing would
# partially undo intentional pullbacks and silences.
# ---------------------------------------------------------------------------

SCORED_SAMPLE_RATE = 48_000
SCORED_CHANNELS = 2
SCORE_MIX_MANIFEST_FILENAME = "score-mix-manifest.json"
SCORE_MIX_WORKFLOW_VERSION = "score-mix-v1"

#: Practical digital silence floor at 16-bit depth (1e-6 * 32767 < 1 LSB).
SILENCE_FLOOR_DB = -120.0
DEFAULT_PULL_BACK_DB = -6.0
DEFAULT_BUILD_DB = 3.0
_LOWPASS_WARMUP_SECONDS = 0.02


class ScoreRenderError(ValueError):
    """The score plan cannot be applied to the soundtrack."""


@dataclass(frozen=True, slots=True)
class _GainSegment:
    start_sample: int
    end_sample: int
    from_db: float
    to_db: float


@dataclass(frozen=True, slots=True)
class _LowpassRegion:
    start_sample: int
    end_sample: int
    cutoff_hz: float
    engage_samples: int
    release_samples: int


def _seconds_to_samples(seconds: float) -> int:
    return int(round(seconds * SCORED_SAMPLE_RATE))


def _db_to_gain(db: float) -> float:
    return 10.0 ** (db / 20.0)


def _clamp16(value: int) -> int:
    if value > 32767:
        return 32767
    if value < -32768:
        return -32768
    return value


def compile_music_envelope(plan: ScorePlan) -> tuple[list[_GainSegment], list[_LowpassRegion]]:
    """Compile cues into a piecewise gain envelope and low-pass regions.

    Build and pull_back cues are *relative* moves: they shift the bed by
    ``gain_db`` (or the action default) from the level the previous cue left
    behind, linearly in dB over the cue's transition window. Silence and
    restore are *absolute* states (digital floor, full level; restore may
    name an explicit absolute target). A cue that lands mid-transition
    interrupts the running ramp: the ramp settles at the new cue's time at
    the level it had actually reached, and the new cue departs from that
    level, so the envelope is continuous and no sample is ramped twice.
    Pullbacks that carry a ``lowpass_hz`` additionally engage a low-pass
    filter for the wet region that runs until the next automation cue
    releases it. Effect cues do not touch the envelope.
    """
    total = _seconds_to_samples(plan.duration_seconds)
    automation = [cue for cue in plan.cues if cue.action in MUSIC_AUTOMATION_ACTIONS]
    segments: list[_GainSegment] = []
    regions: list[_LowpassRegion] = []
    level = 0.0
    open_region: _LowpassRegion | None = None
    #: The transition no later cue has settled yet: (start, end, from, to).
    pending: tuple[int, int, float, float] | None = None

    def close_region(at_sample: int, release_samples: int) -> None:
        nonlocal open_region
        if open_region is not None:
            regions.append(
                _LowpassRegion(
                    open_region.start_sample, at_sample, open_region.cutoff_hz,
                    open_region.engage_samples, release_samples,
                )
            )
            open_region = None

    def settle_pending(at_sample: int) -> float:
        """End the pending transition at ``at_sample`` (the next cue's time).

        An interrupted ramp stops at the level it had actually reached; an
        uninterrupted one runs to its full target. Returns the level the
        envelope reaches at ``at_sample``.
        """
        nonlocal pending
        if pending is None:
            return level
        pstart, pend, pfrom, pto = pending
        pending = None
        if at_sample >= pend:
            segments.append(_GainSegment(pstart, pend, pfrom, pto))
            return pto
        reached = pfrom + (pto - pfrom) * (at_sample - pstart) / (pend - pstart)
        if at_sample > pstart:
            segments.append(_GainSegment(pstart, at_sample, pfrom, reached))
        return reached

    for cue in automation:
        start = _seconds_to_samples(cue.time_seconds)
        transition = _seconds_to_samples(cue.transition_seconds)
        if pending is not None:
            level = settle_pending(start)
        if cue.action is ScoreAction.BUILD:
            target = level + (cue.gain_db if cue.gain_db is not None else DEFAULT_BUILD_DB)
        elif cue.action is ScoreAction.PULL_BACK:
            target = level + (cue.gain_db if cue.gain_db is not None else DEFAULT_PULL_BACK_DB)
        elif cue.action is ScoreAction.SILENCE:
            target = SILENCE_FLOOR_DB
        else:  # restore: full level, or an explicit absolute target
            target = 0.0 if cue.gain_db is None else cue.gain_db
        target = min(GAIN_DB_MAX, max(SILENCE_FLOOR_DB, target))
        new_wet = cue.action is ScoreAction.PULL_BACK and cue.lowpass_hz is not None
        if open_region is not None:
            # A new automation state ends the running filter stretch: the old
            # cutoff releases over this cue's transition (zero transition
            # means a hard release).
            close_region(start, transition)
        if new_wet:
            open_region = _LowpassRegion(start, total, cue.lowpass_hz, transition, 0)
        pending = (start, min(start + max(transition, 1), total), level, target)
        level = target
    settle_pending(total)
    close_region(total, 0)
    return segments, regions


def _biquad_lowpass_coeffs(cutoff_hz: float, sample_rate: float) -> tuple[float, ...]:
    """Second-order Butterworth low-pass (RBJ cookbook), Q = 1/sqrt(2)."""
    q = 0.7071067811865476
    w0 = 2.0 * math.pi * min(max(cutoff_hz, 1.0), sample_rate / 2.0 - 1.0) / sample_rate
    cos_w = math.cos(w0)
    sin_w = math.sin(w0)
    alpha = sin_w / (2.0 * q)
    a0 = 1.0 + alpha
    b0 = (1.0 - cos_w) / 2.0 / a0
    b1 = (1.0 - cos_w) / a0
    b2 = b0
    a1 = (-2.0 * cos_w) / a0
    a2 = (1.0 - alpha) / a0
    return b0, b1, b2, a1, a2


def _filter_mono(values: array, coeffs: tuple[float, ...]) -> array:
    b0, b1, b2, a1, a2 = coeffs
    out = array("d")
    out.extend(values)
    x1 = x2 = y1 = y2 = 0.0
    for index in range(len(out)):
        x = out[index]
        y = b0 * x + b1 * x1 + b2 * x2 - a1 * y1 - a2 * y2
        out[index] = y
        x2, x1 = x1, x
        y2, y1 = y1, y
    return out


def _apply_gain_segments(samples: array, segments: list[_GainSegment], length: int) -> None:
    """Apply the piecewise dB envelope sample-accurately (interleaved stereo)."""
    if not segments:
        return
    channels = SCORED_CHANNELS
    cursor = 0

    def scale(start: int, end: int, gain: float) -> None:
        if gain == 1.0:
            return
        for index in range(start, end):
            for channel in range(channels):
                position = index * channels + channel
                samples[position] = _clamp16(int(round(samples[position] * gain)))

    for segment in segments:
        start = min(max(segment.start_sample, 0), length)
        end = min(segment.end_sample, length)
        if cursor < start:
            scale(cursor, start, _db_to_gain(segment.from_db))
            cursor = start
        ramp_start = max(start, cursor)
        if end > ramp_start:
            if segment.to_db != segment.from_db:
                # Continue the same dB line: a segment whose head was already
                # ramped departs from the level that line had reached at
                # ``ramp_start`` instead of re-ramping samples in place.
                step_db = (segment.to_db - segment.from_db) / (end - start)
                db = segment.from_db + step_db * (ramp_start - start)
                for index in range(ramp_start, end):
                    gain = _db_to_gain(db)
                    for channel in range(channels):
                        position = index * channels + channel
                        samples[position] = _clamp16(int(round(samples[position] * gain)))
                    db += step_db
            else:
                scale(ramp_start, end, _db_to_gain(segment.to_db))
            cursor = end
    if cursor < length:
        scale(cursor, length, _db_to_gain(segments[-1].to_db))


def _apply_lowpass_regions(samples: array, regions: list[_LowpassRegion], length: int) -> None:
    """Crossfade the dry music into a low-passed wet signal per region.

    The filter warms up on a short tail of preceding samples so the engage
    ramp starts from steady-state instead of a biquad transient.
    """
    if not regions:
        return
    channels = SCORED_CHANNELS
    for region in regions:
        start = min(max(region.start_sample, 0), length)
        end = min(region.end_sample, length)
        if end <= start:
            continue
        release = min(max(region.release_samples, 0), end - start)
        engage = min(max(region.engage_samples, 0), end - start)
        warm = min(max(1, _seconds_to_samples(_LOWPASS_WARMUP_SECONDS)), start)
        warm_start = start - warm
        # Split interleaved channels for the region plus warm-up, filter each
        # channel, then crossfade dry/wet per sample.
        dry_channels: list[array] = []
        wet_channels: list[array] = []
        coeffs = _biquad_lowpass_coeffs(region.cutoff_hz, SCORED_SAMPLE_RATE)
        for channel in range(channels):
            dry = samples[channel::channels]
            segment = dry[warm_start:end]
            dry_channels.append(array("h", segment))
            wet_channels.append(_filter_mono(array("d", segment), coeffs))
        for i in range(end - start):
            absolute = start + i
            if i < engage:
                weight = i / engage
            elif release > 0 and absolute >= end - release:
                weight = max(0.0, (end - 1 - absolute) / release)
            else:
                weight = 1.0
            for channel in range(channels):
                position = absolute * channels + channel
                # The channel arrays begin ``warm`` samples before the region
                # so the wet filter is in steady state; offset by ``warm`` so
                # each written sample is the content of its own position.
                mixed = (
                    dry_channels[channel][i + warm] * (1.0 - weight)
                    + wet_channels[channel][i + warm] * weight
                )
                samples[position] = _clamp16(int(round(mixed)))


def score_mix_manifest_path(project_root: Path) -> Path:
    return project_root / "music" / SCORE_MIX_MANIFEST_FILENAME


def load_score_mix_manifest(project_root: Path) -> dict[str, Any] | None:
    """Read the score-mix manifest, or ``None`` when the stage never ran."""
    path = score_mix_manifest_path(project_root)
    if not path.is_file():
        return None
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return None
    return payload if isinstance(payload, dict) else None


def _ffmpeg_version_text(binaries: FFmpegBinaries | None) -> str | None:
    """First line of ``ffmpeg -version`` (e.g. ``ffmpeg version 6.1 ...``)."""
    try:
        ffmpeg = require_ffmpeg(binaries)
    except Exception:
        return None
    try:
        result = subprocess.run(
            [str(ffmpeg), "-version"],
            stdout=subprocess.PIPE, stderr=subprocess.DEVNULL,
            timeout=15.0, check=False,
        )
    except (OSError, subprocess.SubprocessError):
        return None
    if result.returncode != 0:
        return None
    lines = (result.stdout or b"").decode("utf-8", "replace").splitlines()
    return lines[0].strip() if lines else None


def _read_stereo_pcm(
    path: Path, binaries: FFmpegBinaries | None,
) -> array:
    """Read a file as interleaved 48 kHz stereo int16 samples.

    Files already in that exact format are read directly; anything else is
    normalized by FFmpeg into a temporary WAV next to the source.
    """
    try:
        with wave.open(str(path), "rb") as handle:
            if (
                handle.getframerate() == SCORED_SAMPLE_RATE
                and handle.getnchannels() == SCORED_CHANNELS
                and handle.getsampwidth() == 2
            ):
                return array("h", handle.readframes(handle.getnframes()))
    except (wave.Error, EOFError, OSError):
        pass
    if not path.is_file():
        raise ScoreRenderError(f"audio source is missing: {path}")
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{path.name}.scored-", suffix=".wav", dir=path.parent
    )
    os.close(descriptor)
    temporary = Path(temporary_name)
    try:
        argv = [
            str(require_ffmpeg(binaries)),
            "-hide_banner", "-loglevel", "error", "-y",
            "-i", str(path),
            "-af", (
                f"aformat=sample_fmts=s16:sample_rates={SCORED_SAMPLE_RATE}"
                ":channel_layouts=stereo"
            ),
            "-ar", str(SCORED_SAMPLE_RATE),
            "-ac", str(SCORED_CHANNELS),
            "-c:a", "pcm_s16le",
            str(temporary),
        ]
        run_media_process(argv, timeout=300.0)
        with wave.open(str(temporary), "rb") as handle:
            if (
                handle.getframerate() != SCORED_SAMPLE_RATE
                or handle.getnchannels() != SCORED_CHANNELS
            ):
                raise ScoreRenderError(
                    f"FFmpeg produced an unexpected format for {path.name}"
                )
            return array("h", handle.readframes(handle.getnframes()))
    finally:
        temporary.unlink(missing_ok=True)


def _mix_effects(
    samples: array,
    cues: list[ScoreCue],
    decoded: dict[str, array],
    length: int,
) -> None:
    """Add each effect cue's asset at its cue time (music-automation
    independent: an impact stays audible through a silenced bed)."""
    for cue in cues:
        if cue.action not in EFFECT_ACTIONS or cue.effect_path is None:
            continue
        data = decoded.get(cue.effect_path)
        if data is None:
            raise ScoreRenderError(
                f"cue {cue.id} references unreadable effect {cue.effect_path}"
            )
        gain = (
            _db_to_gain(cue.effect_gain_db)
            if cue.effect_gain_db is not None
            else 1.0
        )
        offset = min(_seconds_to_samples(cue.time_seconds), length)
        channels = SCORED_CHANNELS
        for frame in range(len(data) // channels):
            index = offset + frame
            if index >= length:
                break
            for channel in range(channels):
                position = index * channels + channel
                samples[position] = _clamp16(
                    samples[position] + int(round(data[frame * channels + channel] * gain))
                )


def _write_pcm_atomic(path: Path, samples: array) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{path.name}.", suffix=".wav", dir=path.parent
    )
    os.close(descriptor)
    temporary = Path(temporary_name)
    try:
        with wave.open(str(temporary), "wb") as handle:
            handle.setnchannels(SCORED_CHANNELS)
            handle.setsampwidth(2)
            handle.setframerate(SCORED_SAMPLE_RATE)
            handle.writeframes(samples.tobytes())
        with open(temporary, "rb") as handle:
            os.fsync(handle.fileno())
        os.replace(temporary, path)
    except Exception:
        temporary.unlink(missing_ok=True)
        raise


def render_scored_background(
    project_root: Path,
    plan: ScorePlan,
    *,
    binaries: FFmpegBinaries | None = None,
) -> dict[str, Any]:
    """Apply the score plan to ``music/background.wav`` deterministically.

    The source master is never modified: the result lands in
    ``music/scored-background.wav`` (48 kHz stereo PCM) and the manifest in
    ``music/score-mix-manifest.json`` records every input hash, the FFmpeg
    version, the cue-plan hash, and the output hash. Cue automation is
    sample-accurate and is never re-normalized afterward.

    Returns the written manifest. Raises :class:`ScoreRenderError` when the
    soundtrack or an effect reference is unusable.
    """
    music_root = project_root / "music"
    background = music_root / "background.wav"
    if not background.is_file():
        raise ScoreRenderError(
            "music/background.wav is missing; generate the soundtrack before scoring it"
        )
    validate_score_plan_effects(project_root, plan)

    output = scored_background_path(project_root)
    length = _seconds_to_samples(plan.duration_seconds)
    samples = _read_stereo_pcm(background, binaries)

    # Trim or pad the bed to the narration-driven score length first so every
    # later operation works on exactly the right number of samples.
    frames = len(samples) // SCORED_CHANNELS
    if frames > length:
        samples = array("h", samples[: length * SCORED_CHANNELS])
    elif frames < length:
        samples.extend(array("h", bytes(2 * SCORED_CHANNELS * (length - frames))))

    segments, regions = compile_music_envelope(plan)
    _apply_lowpass_regions(samples, regions, length)
    _apply_gain_segments(samples, segments, length)

    decoded: dict[str, array] = {}
    for cue in plan.cues:
        if (
            cue.action in EFFECT_ACTIONS
            and cue.effect_path is not None
            and cue.effect_path not in decoded
        ):
            effect_path = resolve_cue_effect_path(project_root, cue)
            decoded[cue.effect_path] = _read_stereo_pcm(effect_path, binaries)
    _mix_effects(samples, plan.cues, decoded, length)

    _write_pcm_atomic(output, samples)

    relative = lambda path: str(Path(path).relative_to(project_root))  # noqa: E731
    manifest: dict[str, Any] = {
        "version": 1,
        "workflow_version": SCORE_MIX_WORKFLOW_VERSION,
        "sample_rate": SCORED_SAMPLE_RATE,
        "channels": SCORED_CHANNELS,
        "loudness_normalization": False,
        "ffmpeg_version": _ffmpeg_version_text(binaries),
        "source": {
            "path": relative(background),
            "sha256": hash_audio_file(background),
            "plan_duration_seconds": plan.duration_seconds,
        },
        "plan": {
            "path": relative(score_plan_path(project_root)),
            "plan_hash": score_plan_hash(plan),
            "revision": plan.revision,
            "cue_count": len(plan.cues),
        },
        "effects": [
            {
                "cue_id": cue.id,
                "path": relative(resolve_cue_effect_path(project_root, cue)),
                "sha256": hash_audio_file(resolve_cue_effect_path(project_root, cue)),
            }
            for cue in plan.cues
            if cue.action in EFFECT_ACTIONS and cue.effect_path is not None
        ],
        "output": {
            "path": relative(output),
            "sha256": hash_audio_file(output),
            "duration_seconds": length / SCORED_SAMPLE_RATE,
        },
        "generated_at": utc_now().isoformat(),
    }
    _atomic_write_json(score_mix_manifest_path(project_root), manifest)
    return manifest


# ---------------------------------------------------------------------------
# Score preview: a fast narration-plus-score monitor
#
# The final video render mixes narration and the scored bed through the normal
# timeline. The Studio's *score preview* is a much cheaper stand-in: it reuses
# the already-rendered ``scored-background.wav`` (rendering it only when the
# plan is newer than the cached mix) and mixes the narration master over it as
# 48 kHz stereo PCM. The result is a rough listening check for cue moves, not
# the deliverable mix, so it deliberately applies no loudness normalization and
# no ducking: the music keeps exactly the level the automation produced.
# ---------------------------------------------------------------------------

SCORE_PREVIEW_FILENAME = "score-preview.wav"
SCORE_PREVIEW_MANIFEST_FILENAME = "score-preview-manifest.json"
SCORE_PREVIEW_WORKFLOW_VERSION = "score-preview-v1"

#: Basenames the Studio may stream straight from ``music/`` by name. Anything
#: else is rejected so a crafted path can never read outside the project.
SCORE_MEDIA_FILES = frozenset(
    {
        "background.wav",
        SCORED_OUTPUT_FILENAME,
        SCORE_PREVIEW_FILENAME,
        SCORE_PLAN_FILENAME,
        "manifest.json",
        SCORE_MIX_MANIFEST_FILENAME,
        SCORE_PREVIEW_MANIFEST_FILENAME,
    }
)


def score_preview_path(project_root: Path) -> Path:
    return project_root / "music" / SCORE_PREVIEW_FILENAME


def score_preview_manifest_path(project_root: Path) -> Path:
    return project_root / "music" / SCORE_PREVIEW_MANIFEST_FILENAME


def load_score_preview_manifest(project_root: Path) -> dict[str, Any] | None:
    """Read the preview manifest, or ``None`` when the preview never ran."""
    path = score_preview_manifest_path(project_root)
    if not path.is_file():
        return None
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return None
    return payload if isinstance(payload, dict) else None


def decode_stereo_pcm(path: Path, binaries: FFmpegBinaries | None = None) -> array:
    """Read a file as interleaved 48 kHz stereo int16 samples (public API).

    Public wrapper over the renderer's normalizer so the score preview can
    consume the narration master and the scored bed with the same guarantees:
    exact-format files are read directly, anything else is normalized.
    """
    return _read_stereo_pcm(path, binaries)


def encode_stereo_pcm(path: Path, samples: array) -> None:
    """Atomically write interleaved 48 kHz stereo int16 samples (public API)."""
    _write_pcm_atomic(path, samples)


def mix_stereo(
    destination: array,
    addend: array,
    *,
    gain_db: float = 0.0,
    max_frames: int | None = None,
) -> None:
    """Add ``addend`` into ``destination`` in place, sample-accurate and clamped.

    Both buffers are interleaved 48 kHz stereo. The sum is limited to
    ``max_frames`` (or the shorter buffer) and clipped to the 16-bit range; no
    normalization is applied, matching the score renderer's automation policy.
    """
    channels = SCORED_CHANNELS
    frames = min(len(destination) // channels, len(addend) // channels)
    if max_frames is not None:
        frames = min(frames, max_frames)
    if frames <= 0:
        return
    gain = _db_to_gain(gain_db) if gain_db else 1.0
    for frame in range(frames):
        for channel in range(channels):
            position = frame * channels + channel
            destination[position] = _clamp16(
                destination[position] + int(round(addend[position] * gain))
            )


def render_score_preview(
    project_root: Path,
    *,
    scored_path: Path,
    narration_path: Path | None = None,
    binaries: FFmpegBinaries | None = None,
) -> dict[str, Any]:
    """Mix the narration master over an already-scored bed into a preview.

    ``scored_path`` is the ``scored-background.wav`` produced by the score
    stage (or the untouched master for an unscored project). The narration is
    optional: without it the preview is simply the scored music. The output is
    48 kHz stereo PCM at the scored bed's length; the manifest records every
    input and output hash plus the FFmpeg version used for normalization.

    Returns the written manifest. Raises :class:`ScoreRenderError` when the
    scored bed is missing or unreadable.
    """
    if not scored_path.is_file():
        raise ScoreRenderError(
            "scored background is missing; generate and score the soundtrack first"
        )
    output = score_preview_path(project_root)
    samples = _read_stereo_pcm(scored_path, binaries)
    has_narration = narration_path is not None and narration_path.is_file()
    if has_narration:
        narration = _read_stereo_pcm(narration_path, binaries)
        mix_stereo(samples, narration, max_frames=len(samples) // SCORED_CHANNELS)

    _write_pcm_atomic(output, samples)
    frames = len(samples) // SCORED_CHANNELS

    def _relative(path: Path) -> str:
        try:
            return str(Path(path).relative_to(project_root))
        except ValueError:
            return Path(path).name

    manifest: dict[str, Any] = {
        "version": 1,
        "workflow_version": SCORE_PREVIEW_WORKFLOW_VERSION,
        "sample_rate": SCORED_SAMPLE_RATE,
        "channels": SCORED_CHANNELS,
        "loudness_normalization": False,
        "ffmpeg_version": _ffmpeg_version_text(binaries),
        "scored": {
            "path": _relative(scored_path),
            "sha256": hash_audio_file(scored_path),
        },
        "narration": (
            {
                "path": _relative(narration_path),
                "sha256": hash_audio_file(narration_path),
            }
            if has_narration
            else None
        ),
        "output": {
            "path": _relative(output),
            "sha256": hash_audio_file(output),
            "duration_seconds": frames / SCORED_SAMPLE_RATE,
        },
        "generated_at": utc_now().isoformat(),
    }
    _atomic_write_json(score_preview_manifest_path(project_root), manifest)
    return manifest
