"""Score plan: timeline cues over the generated soundtrack, plus persistence.

ACE-Step composes the underlying music but does not honor exact timestamps.
Exact musical moves (pullbacks, silences, impacts) are therefore described by
a *score plan* that is applied afterward, deterministically, by FFmpeg:

    music/background.wav  +  music/score-plan.json  ->  music/scored-background.wav

``background.wav`` is never modified; it remains the original generated master.

The models here define the portable, human-readable ``score-plan.json``
schema (version 1), validate every cue, and read/write the plan atomically.
Rendering the automation into audio is a separate concern (the deterministic
``score_mix`` pipeline stage) that consumes exactly these models.
"""

from __future__ import annotations

import hashlib
import json
import os
import re
import tempfile
from datetime import datetime
from enum import StrEnum
from pathlib import Path
from typing import Any

from pydantic import Field, field_validator, model_validator

from backend.schemas.models import DomainModel, new_id, utc_now
from backend.schemas.paths import portable_relative_path, resolve_project_path

#: Portable schema version written by this module and the only one accepted
#: when loading. Older or newer files require an explicit migration.
SCORE_PLAN_VERSION = 1

#: Project-relative artifact names (inside ``<project>/music/``).
SCORE_PLAN_FILENAME = "score-plan.json"
SCORED_OUTPUT_FILENAME = "scored-background.wav"
EFFECTS_DIRECTORY = "music/effects"

#: Guardrail bounds shared with the score renderer and the Score Studio UI.
MAX_TRANSITION_SECONDS = 5.0
GAIN_DB_MIN = -60.0
GAIN_DB_MAX = 12.0
LOWPASS_HZ_MIN = 200.0
LOWPASS_HZ_MAX = 20_000.0
#: Sanity bound for soundtrack/plan duration: 24 hours.
MAX_DURATION_SECONDS = 24 * 3600

DEFAULT_CUE_TRANSITION_SECONDS = 0.25

_HEX_HASH = re.compile(r"^[0-9a-f]{8,64}$")


class ScoreAction(StrEnum):
    """MVP cue vocabulary.

    Music-automation actions reshape the background bed from their cue time
    onward; effect actions mix a one-shot asset in at the cue time.
    """

    BUILD = "build"
    PULL_BACK = "pull_back"
    SILENCE = "silence"
    RESTORE = "restore"
    IMPACT = "impact"
    RISER = "riser"
    END_STING = "end_sting"


#: Actions that change the music envelope (gain/filter automation).
MUSIC_AUTOMATION_ACTIONS = frozenset(
    {ScoreAction.BUILD, ScoreAction.PULL_BACK, ScoreAction.SILENCE, ScoreAction.RESTORE}
)
#: Actions that mix in a one-shot audio asset.
EFFECT_ACTIONS = frozenset(
    {ScoreAction.IMPACT, ScoreAction.RISER, ScoreAction.END_STING}
)


class ScoreCueSource(StrEnum):
    """Where a cue came from; Auto Score must never overwrite MANUAL cues."""

    MANUAL = "manual"
    AUTO = "auto"


class ScorePlanConflict(RuntimeError):
    """The plan changed on disk since the caller last read it."""


class ScoreCue(DomainModel):
    """One timed musical move on the soundtrack timeline.

    Field relevance depends on ``action``: automation cues use
    ``gain_db``/``lowpass_hz``/``transition_seconds``; effect cues use
    ``effect_asset_id``/``effect_path``/``effect_gain_db``. Irrelevant fields
    are preserved (not rejected) so round-trips are lossless, and the
    renderer ignores them.
    """

    # Stable identity: assigned once at creation, never regenerated by
    # sorting, editing order, or persistence round-trips.
    id: str = Field(default_factory=new_id, min_length=1, max_length=64)
    time_seconds: float = Field(ge=0, le=MAX_DURATION_SECONDS, allow_inf_nan=False)
    action: ScoreAction
    label: str = Field(default="", max_length=200)
    transition_seconds: float = Field(
        default=DEFAULT_CUE_TRANSITION_SECONDS,
        ge=0,
        le=MAX_TRANSITION_SECONDS,
        allow_inf_nan=False,
    )
    # Music automation parameters (automation cues only).
    gain_db: float | None = Field(
        default=None, ge=GAIN_DB_MIN, le=GAIN_DB_MAX, allow_inf_nan=False
    )
    lowpass_hz: float | None = Field(
        default=None, ge=LOWPASS_HZ_MIN, le=LOWPASS_HZ_MAX, allow_inf_nan=False
    )
    # Effect sourcing (effect cues only). ``effect_path`` is a portable
    # project-relative path; ``effect_asset_id`` refers to a registered
    # project effect asset.
    effect_asset_id: str | None = Field(default=None, min_length=1, max_length=100)
    effect_path: str | None = Field(default=None, max_length=500)
    effect_gain_db: float | None = Field(
        default=None, ge=GAIN_DB_MIN, le=GAIN_DB_MAX, allow_inf_nan=False
    )
    source: ScoreCueSource = ScoreCueSource.MANUAL
    locked: bool = False

    @field_validator("effect_path", mode="before")
    @classmethod
    def portable_effect_path(cls, value: Any) -> Any:
        if value is None or isinstance(value, str):
            if value is None:
                return None
            # Rejects absolute paths, drive letters, UNC, and .. traversal
            # before the value is ever persisted.
            return portable_relative_path(value)
        return value


class ScorePlan(DomainModel):
    """Portable cue plan over one generated soundtrack.

    ``source_music_hash`` and ``source_backend`` record where the scored
    master came from; ``revision`` is the monotonic save counter used for
    optimistic concurrency; cues are always ordered by ``time_seconds``.
    """

    version: int = SCORE_PLAN_VERSION
    duration_seconds: float = Field(
        gt=0, le=MAX_DURATION_SECONDS, allow_inf_nan=False
    )
    source_music_hash: str | None = None
    source_backend: str = Field(default="unknown", max_length=80)
    revision: int = Field(default=1, ge=0)
    updated_at: datetime = Field(default_factory=utc_now)
    cues: list[ScoreCue] = Field(default_factory=list)

    @field_validator("version")
    @classmethod
    def supported_version(cls, value: int) -> int:
        if value != SCORE_PLAN_VERSION:
            raise ValueError(
                f"unsupported score plan version {value}; this build reads version {SCORE_PLAN_VERSION}"
            )
        return value

    @field_validator("source_music_hash", mode="before")
    @classmethod
    def normalize_source_hash(cls, value: Any) -> Any:
        if value is None:
            return None
        if isinstance(value, str):
            text = value.strip().lower()
            if not text:
                return None
            if not _HEX_HASH.fullmatch(text):
                raise ValueError("source_music_hash must be a hex sha256 digest")
            return text
        return value

    @model_validator(mode="after")
    def normalize_and_validate_cues(self) -> "ScorePlan":
        ids = [cue.id for cue in self.cues]
        if len(ids) != len(set(ids)):
            duplicates = sorted({i for i in ids if ids.count(i) > 1})
            raise ValueError(f"duplicate cue ids: {', '.join(duplicates)}")
        # Deterministic ordering: stable sort keeps equal-time cues in input
        # order and carries each cue's id along with it.
        ordered = sorted(self.cues, key=lambda cue: cue.time_seconds)
        if ordered != self.cues:
            object.__setattr__(self, "cues", ordered)
        for cue in self.cues:
            if cue.time_seconds > self.duration_seconds:
                raise ValueError(
                    f"cue {cue.id} at {cue.time_seconds}s is past the end of the "
                    f"soundtrack ({self.duration_seconds}s)"
                )
        return self


def empty_score_plan(
    duration_seconds: float,
    *,
    source_music_hash: str | None = None,
    source_backend: str = "unknown",
) -> ScorePlan:
    """A valid, cue-less plan for a soundtrack of the given length."""
    return ScorePlan(
        duration_seconds=duration_seconds,
        source_music_hash=source_music_hash,
        source_backend=source_backend,
    )


def score_plan_path(project_root: Path) -> Path:
    return project_root / "music" / SCORE_PLAN_FILENAME


def scored_background_path(project_root: Path) -> Path:
    """Render target consumed by the timeline; never overwrites background.wav."""
    return project_root / "music" / SCORED_OUTPUT_FILENAME


def load_score_plan(project_root: Path) -> ScorePlan | None:
    """Read and validate the plan, or ``None`` when the project is unscored.

    A missing file is the normal "no score" state. A malformed plan raises so
    callers can surface the problem instead of silently ignoring cues.
    """
    path = score_plan_path(project_root)
    if not path.is_file():
        return None
    return ScorePlan.model_validate_json(path.read_text(encoding="utf-8"))


def save_score_plan(
    project_root: Path,
    plan: ScorePlan,
    *,
    expected_revision: int | None = None,
) -> ScorePlan:
    """Atomically persist ``plan`` and return the saved plan.

    With ``expected_revision`` set, the plan on disk must still carry that
    revision (0 when absent): a stale editor gets :class:`ScorePlanConflict`
    instead of silently overwriting newer work, and the saved copy is stamped
    with ``expected_revision + 1``. Without it the caller keeps full control
    of the revision (internal tooling, migrations).
    """
    current = load_score_plan(project_root)
    current_revision = current.revision if current is not None else 0
    if expected_revision is not None and current_revision != expected_revision:
        raise ScorePlanConflict(
            "score plan changed since it was loaded: expected revision "
            f"{expected_revision}, found {current_revision}"
        )
    updates: dict[str, Any] = {"updated_at": utc_now()}
    if expected_revision is not None:
        updates["revision"] = current_revision + 1
    saved = plan.model_copy(update=updates)
    _atomic_write_json(score_plan_path(project_root), saved.model_dump(mode="json"))
    return saved


def score_plan_hash(plan: ScorePlan) -> str:
    """Stable 16-hex content digest of the score.

    Ignores ``revision`` and ``updated_at`` so re-saving an unchanged score
    (or bumping provenance metadata) never changes the digest; the score_mix
    stage uses this as its cache key alongside the source music hash.
    """
    payload: dict[str, Any] = {
        "version": plan.version,
        "duration_seconds": round(plan.duration_seconds, 6),
        "source_music_hash": plan.source_music_hash,
        "cues": [cue.model_dump(mode="json") for cue in plan.cues],
    }
    return hashlib.sha256(
        json.dumps(payload, sort_keys=True, ensure_ascii=False).encode("utf-8")
    ).hexdigest()[:16]


def hash_audio_file(path: Path, *, block_size: int = 1024 * 1024) -> str:
    """Streaming sha256 of a soundtrack/effect file, for plan provenance."""
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        while True:
            chunk = handle.read(block_size)
            if not chunk:
                break
            digest.update(chunk)
    return digest.hexdigest()


def resolve_cue_effect_path(project_root: Path, cue: ScoreCue) -> Path | None:
    """Resolve a cue's project-relative effect path, rejecting escapes.

    Raises ``ValueError`` for traversal or symlink escapes; returns ``None``
    when the cue references an asset registry id instead of a path.
    """
    if cue.effect_path is None:
        return None
    return resolve_project_path(project_root, cue.effect_path)


def validate_score_plan_effects(project_root: Path, plan: ScorePlan) -> None:
    """Check every effect reference on a cue plan against the project tree.

    Paths must resolve inside the project directory (no traversal, no symlink
    escapes) and point at an existing file. Asset-id references are resolved
    by the effect registry layer and are skipped here.
    """
    problems: list[str] = []
    for cue in plan.cues:
        if cue.effect_path is None:
            continue
        try:
            resolved = resolve_cue_effect_path(project_root, cue)
        except ValueError as exc:
            problems.append(f"cue {cue.id}: {exc}")
            continue
        if resolved is not None and not resolved.is_file():
            problems.append(
                f"cue {cue.id}: effect file not found: {cue.effect_path}"
            )
    if problems:
        raise ValueError("; ".join(problems))


def _atomic_write_json(path: Path, payload: Any) -> None:
    """Crash-safe JSON write matching the project store's conventions."""
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{path.name}.", dir=path.parent
    )
    temporary = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
            json.dump(payload, handle, indent=2, sort_keys=True, ensure_ascii=False)
            handle.write("\n")
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary, path)
    except Exception:
        temporary.unlink(missing_ok=True)
        raise
