"""Generator adapters, shot-lane resolution, and discovery."""

from .ace_step_comfyui import ACEStepComfyUIBackend
from .adapters import (
    ChatterboxBackend,
    FluxBackend,
    H3Backend,
    Ideogram4LocalBackend,
    Krea2Backend,
    QwenImage2512Backend,
    WanBackend,
    WhisperBackend,
)
from .base import (
    BackendDescriptor,
    Capability,
    GenerationRequest,
    GenerationResult,
    GeneratorBackend,
)
from .comfyui import ComfyUIBackend
from .faster_whisper import FasterWhisperBackend
from .h3_shot_continuity import (
    H3_NATIVE_AUDIO_MIX_POLICY,
    ShotContinuityError,
    ShotContinuityErrorCode,
    ShotContinuityLink,
    build_shots_index,
    direct_dependents,
    effective_predecessor_shot_id,
    last_eligible_h3_shot_id,
    mark_dependents_stale,
    native_audio_policy,
    order_for_serial_execution,
    parse_shot_continuity,
    stale_closure,
    timeline_key,
    validate_continuity_chain,
)
from .lane_resolver import (
    DETERMINISTIC_HANDLERS,
    LANE_TARGETS,
    PENDING_HANDLERS,
    LaneErrorCode,
    LaneResolutionError,
    LaneTarget,
    ResolvedLaneTarget,
    describe_lane_targets,
    resolve_lane_target,
)
from .local_llm import LocalLLMBackend
from .ideogram_prompt import (
    IdeogramComposition,
    IdeogramObjectElement,
    IdeogramPrompt,
    IdeogramPromptError,
    IdeogramStyle,
    IdeogramTextElement,
    build_ideogram_v4_prompt,
    export_kjnodes_ideogram_json,
    import_kjnodes_ideogram_json,
)
from .mock import MockGeneratorBackend, MockLLMBackend
from .provenance import (
    RegenerationImpact,
    apply_regeneration_staleness,
    current_visual_asset,
    dependency_edges,
    plan_regeneration,
    provenance_summary,
)
from .registry import BackendRegistry
from .shot_requests import (
    ResolvedReference,
    ShotGenerationPlan,
    ShotRequestError,
    build_h3_request,
    build_krea2_request,
    build_qwen_image_request,
    build_shot_request,
    resolve_reference_assets,
)
from .tts_service import TTSServiceBackend

__all__ = [
    "ACEStepComfyUIBackend",
    "PENDING_HANDLERS",
    "BackendDescriptor",
    "BackendRegistry",
    "Capability",
    "ChatterboxBackend",
    "ComfyUIBackend",
    "DETERMINISTIC_HANDLERS",
    "FluxBackend",
    "FasterWhisperBackend",
    "GenerationRequest",
    "GenerationResult",
    "GeneratorBackend",
    "H3Backend",
    "H3_NATIVE_AUDIO_MIX_POLICY",
    "Ideogram4LocalBackend",
    "IdeogramComposition",
    "IdeogramObjectElement",
    "IdeogramPrompt",
    "IdeogramPromptError",
    "IdeogramStyle",
    "IdeogramTextElement",
    "Krea2Backend",
    "LANE_TARGETS",
    "LaneErrorCode",
    "LaneResolutionError",
    "LaneTarget",
    "LocalLLMBackend",
    "MockGeneratorBackend",
    "MockLLMBackend",
    "QwenImage2512Backend",
    "RegenerationImpact",
    "ResolvedLaneTarget",
    "ResolvedReference",
    "ShotContinuityError",
    "ShotContinuityErrorCode",
    "ShotContinuityLink",
    "ShotGenerationPlan",
    "ShotRequestError",
    "TTSServiceBackend",
    "WanBackend",
    "WhisperBackend",
    "apply_regeneration_staleness",
    "build_h3_request",
    "build_ideogram_v4_prompt",
    "build_krea2_request",
    "build_qwen_image_request",
    "build_shot_request",
    "build_shots_index",
    "current_visual_asset",
    "dependency_edges",
    "describe_lane_targets",
    "direct_dependents",
    "effective_predecessor_shot_id",
    "export_kjnodes_ideogram_json",
    "import_kjnodes_ideogram_json",
    "last_eligible_h3_shot_id",
    "mark_dependents_stale",
    "native_audio_policy",
    "order_for_serial_execution",
    "parse_shot_continuity",
    "plan_regeneration",
    "provenance_summary",
    "resolve_lane_target",
    "resolve_reference_assets",
    "stale_closure",
    "timeline_key",
    "validate_continuity_chain",
]
